version: '3.2'

services:
  elasticsearch:
    build:
      context: src/Resources/docker/elasticsearch
      dockerfile: Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    labels:
      traefik.enabled: "false"
    networks:
      - app_network_backend

  logstash:
    build:
      context: src/Resources/docker/logstash
      dockerfile: Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - app_network_backend
    labels:
      traefik.enabled: "false"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: src/Resources/docker/kibana
      dockerfile: Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5601:5601"
    labels:
      traefik.port: 5601
      traefik.frontend.rule: "Host:kibana.example.dev"
    networks:
      - app_network_backend
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: src/Resources/docker/filebeat
      dockerfile: Dockerfile
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
    volumes:
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    labels:
      traefik.enabled: "false"
    networks:
      - app_network_backend
    depends_on:
      - kibana

networks:
  app_network_backend:
    external: true

volumes:
  elasticsearch:
