filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTIC_HOST:elasticsearch:9200}'
  username: '${ELASTIC_USERNAME:elastic}'
  password: '${ELASTIC_PASSWORD:changeme}'

#output.logstash:
#  hosts: '${LOGSTASH_HOSTS:logstash:5044}'

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true